# Copyright 2016 the HERA collaboration.
# Licensed under the BSD License.
# This file requires Docker >= v1.10 and docker-compose >= v1.6.
version: "2"

services:
  db:
    image: hera-test-db
    hostname: db
    environment:
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    networks:
      - hera
    expose:
      - "5432"

  onsitelibrarian:
    image: hera-test-librarian
    hostname: onsitelibrarian
    command: /launch.sh onsite
    depends_on:
      - db
    environment:
      HERA_DB_PASSWORD: "$DB_PASSWORD"
    networks:
      - hera
    ports:
      - "21106:21106"
    volumes:
      - ./onsitelibrarian:/data

  onsitepot:
    image: hera-rsync-pot
    hostname: onsitepot
    environment:
      HERA_DB_PASSWORD: "$DB_PASSWORD"
    networks:
      - hera
    volumes:
      - ./onsitepot:/data

  offsitelibrarian:
    image: hera-test-librarian
    hostname: offsitelibrarian
    command: /launch.sh offsite
    depends_on:
      - db
    environment:
      HERA_DB_PASSWORD: "$DB_PASSWORD"
    networks:
      - hera
    ports:
      - "21107:21106"
    volumes:
      - ./offsitelibrarian:/data

  offsitepot:
    image: hera-rsync-pot
    hostname: offsitepot
    environment:
      HERA_DB_PASSWORD: "$DB_PASSWORD"
    networks:
      - hera
    volumes:
      - ./offsitepot:/data

networks:
  hera:
    driver: bridge
